replicaCount: 1

image:
  repository: kargo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

namespace: test